CREATE DATABASE lyonpalme;

use lyonpalme;

CREATE TABLE ADHERENT(
   ADHNum VARCHAR(50),
   ADHNom VARCHAR(50),
   ADHPrenom VARCHAR(50),
   ADHDatenaissance DATE,
   ADHDatecertmedical DATE,
   ADHFonctionBureau VARCHAR(50) UNIQUE,
   ADHAutreFonction VARCHAR(50) UNIQUE,
   ADHId VARCHAR(50) UNIQUE,
   ADHMdp VARCHAR(50) UNIQUE,
   PRIMARY KEY(ADHNum)
);

CREATE TABLE COMPETITION(
   COMPNum VARCHAR(50),
   COMPLibelle VARCHAR(50),
   COMPFinInscription VARCHAR(50),
   PRIMARY KEY(COMPNum)
);

CREATE TABLE MATERIEL(
   MATNum VARCHAR(50),
   MATLibelle VARCHAR(100),
   MATMarque VARCHAR(50),
   MATTaille DECIMAL(15,2),
   PRIMARY KEY(MATNum)
);

CREATE TABLE ENTRAINEUR(
   ADHNum VARCHAR(50),
   PRIMARY KEY(ADHNum),
   FOREIGN KEY(ADHNum) REFERENCES ADHERENT(ADHNum)
);

CREATE TABLE COACH(
   ADHNum VARCHAR(50),
   PRIMARY KEY(ADHNum),
   FOREIGN KEY(ADHNum) REFERENCES ENTRAINEUR(ADHNum)
);

CREATE TABLE CALENDRIER(
   DatePretMateriel DATE,
   PRIMARY KEY(DatePretMateriel)
);

CREATE TABLE MODALITE(
   MODNum VARCHAR(50),
   MODLIbelle VARCHAR(50),
   PRIMARY KEY(MODNum)
);

CREATE TABLE DISTANCE(
   METRES_DISTANCE INT,
   PRIMARY KEY(METRES_DISTANCE)
);

CREATE TABLE SORTIE(
   SORTIENum VARCHAR(50),
   SORTIEHeureDebut TIME,
   SORTIELieu VARCHAR(50),
   SORTIEPlage VARCHAR(50),
   SORTIENiveauPublic VARCHAR(50),
   SORTIEMentionObligatoire VARCHAR(50),
   SORTIEMentionHiver VARCHAR(50),
   ADHNum VARCHAR(50) NOT NULL,
   PRIMARY KEY(SORTIENum),
   FOREIGN KEY(ADHNum) REFERENCES ENTRAINEUR(ADHNum)
);

CREATE TABLE ENTRAINEMENT(
   ENTRAINEMENTNum VARCHAR(50),
   ENTRAINEMENTDate DATE,
   ADHNum VARCHAR(50) NOT NULL,
   PRIMARY KEY(ENTRAINEMENTNum),
   FOREIGN KEY(ADHNum) REFERENCES COACH(ADHNum)
);

CREATE TABLE SEANCE(
   SEANCENum VARCHAR(50),
   SEANCEDate VARCHAR(50),
   SEANCEContenu VARCHAR(50),
   ENTRAINEMENTNum VARCHAR(50) NOT NULL,
   PRIMARY KEY(SEANCENum),
   FOREIGN KEY(ENTRAINEMENTNum) REFERENCES ENTRAINEMENT(ENTRAINEMENTNum)
);

CREATE TABLE S_INSCRIRE(
   ADHNum VARCHAR(50),
   SORTIENum VARCHAR(50),
   PRIMARY KEY(ADHNum, SORTIENum),
   FOREIGN KEY(ADHNum) REFERENCES ADHERENT(ADHNum),
   FOREIGN KEY(SORTIENum) REFERENCES SORTIE(SORTIENum)
);

CREATE TABLE PRETER(
   MATNum VARCHAR(50),
   DatePretMateriel DATE,
   PRETERDate DATE,
   ADHNum VARCHAR(50) NOT NULL,
   PRIMARY KEY(MATNum, DatePretMateriel),
   FOREIGN KEY(MATNum) REFERENCES MATERIEL(MATNum),
   FOREIGN KEY(DatePretMateriel) REFERENCES CALENDRIER(DatePretMateriel),
   FOREIGN KEY(ADHNum) REFERENCES ADHERENT(ADHNum)
);

CREATE TABLE PARTICIPERCOMP(
   ADHNum VARCHAR(50),
   COMPNum VARCHAR(50),
   PARTModaliteChoisie VARCHAR(50),
   PARTDistanceChoisie INT,
   PARTBesoinCovoiturage VARCHAR(50),
   PARTProposerCovoiturage VARCHAR(50),
   PARTNbPlacesVoiture INT,
   PARTHebergement VARCHAR(50),
   PARTNbPersonneAccompagnee VARCHAR(50),
   PRIMARY KEY(ADHNum, COMPNum),
   FOREIGN KEY(ADHNum) REFERENCES ADHERENT(ADHNum),
   FOREIGN KEY(COMPNum) REFERENCES COMPETITION(COMPNum)
);

CREATE TABLE FAIRE(
   ADHNum VARCHAR(50),
   SEANCENum VARCHAR(50),
   FAIREIndispo VARCHAR(50),
   FAIREProposerEchanger VARCHAR(50),
   PRIMARY KEY(ADHNum, SEANCENum),
   FOREIGN KEY(ADHNum) REFERENCES ENTRAINEUR(ADHNum),
   FOREIGN KEY(SEANCENum) REFERENCES SEANCE(SEANCENum)
);

CREATE TABLE PROPOSERMOD(
   COMPNum VARCHAR(50),
   MODNum VARCHAR(50),
   PRIMARY KEY(COMPNum, MODNum),
   FOREIGN KEY(COMPNum) REFERENCES COMPETITION(COMPNum),
   FOREIGN KEY(MODNum) REFERENCES MODALITE(MODNum)
);

CREATE TABLE PROPOSERDIST(
   COMPNum VARCHAR(50),
   METRES_DISTANCE INT,
   PRIMARY KEY(COMPNum, METRES_DISTANCE),
   FOREIGN KEY(COMPNum) REFERENCES COMPETITION(COMPNum),
   FOREIGN KEY(METRES_DISTANCE) REFERENCES DISTANCE(METRES_DISTANCE)
);
