CREATE TABLE PARTICIPER(
   ADHNum VARCHAR(50),
   SEANCENum VARCHAR(50),
   PRIMARY KEY(ADHNum, SEANCENum),
   FOREIGN KEY(ADHNum) REFERENCES ADHERENT(ADHNum),
   FOREIGN KEY(SEANCENum) REFERENCES SEANCE(SEANCENum)
);
